# ワークフローの名前。
name: Build

# どういったイベントが発生したときにワークフローを実行するかを指定。
on:
  # ここでは変更がpushされたときをイベントとして指定。
  - main

# ワークフローが実行するジョブの一覧
jobs:
  # ビルドを行うジョブ
  build:
    # 最新のUbuntuでワークフローを実行
    runs-on: ubuntu-latest
    # ジョブが行うステップの一覧
    steps:
      # ソースコードをGitからチェックアウト
      - uses: actions/checkout@v2
      # Gradleラッパースクリプトが正しいものか確認
      - uses: gradle/wrapper-validation-action@v1
      # Java 11 を使えるようにする
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Gradleビルドを実行
      - run: |
          ./gradlew build